#pragma once

#include <cstdint>

enum class opcodes : uint16_t
{
    PKTAbilityChangeNotify = 0,
    PKTActiveAbilityNotify = 0,
    PKTAddonSkillFeatureChangeNotify = 0,
    PKTAuthTokenResult = 0,
    PKTBlockSkillStateNotify = 0x40A0,
    PKTChatWhisperError = 0xD9D8,
    PKTCounterAttackNotify = 0,
    PKTDeathNotify = 0,
    PKTEquipChangeNotify = 0,
    PKTEquipLifeToolChangeNotify = 0,
    PKTHyperGaugeChangeNotify = 0,
    PKTIdentityChangeNotify = 0,
    PKTIdentityGaugeChangeNotify = 0,
    PKTIdentityStanceChangeNotify = 0,
    PKTInitAbility = 0,
    PKTInitEnv = 0,
    PKTInitItem = 0,
    PKTInitLocal = 0,
    PKTInitPC = 0,
    PKTInstanceZoneEnteredNotify = 0,
    PKTKeyExchangeClient = 0x56BD,
    PKTKeyExchangeServer = 0x2C54,
    PKTMigrationExecute = 0,
    PKTMoveNotify = 0x8C25,
    PKTMoveStopNotify = 0xD54F,
    PKTNewDropBox = 0x2DD0,
    PKTNewNpc = 0,
    PKTNewNpcSummon = 0,
    PKTNewPC = 0,
    PKTNewProjectile = 0,
    PKTNewTrap = 0,
    PKTParalyzationStateNotify = 0,
    PKTPartyInfo = 0,
    PKTPartyLeaveResult = 0,
    PKTPartyPassiveStatusEffectAddNotify = 0,
    PKTPartyPassiveStatusEffectRemoveNotify = 0,
    PKTPartyStatusEffectAddNotify = 0,
    PKTPartyStatusEffectRemoveNotify = 0,
    PKTPartyStatusEffectResultNotify = 0,
    PKTPassiveStatusEffectAddNotify = 0,
    PKTPassiveStatusEffectRemoveNotify = 0,
    PKTPCInspectResult = 0,
    PKTPickupDropBoxResult = 0x47CC,
    PKTRaidBegin = 0,
    PKTRaidBossKillNotify = 0,
    PKTRaidResult = 0,
    PKTRemoveObject = 0x9F07,
    PKTSkillCancelNotify = 0,
    PKTSkillCastNotify = 0,
    PKTSkillCooldownNotify = 0,
    PKTSkillDamageAbnormalMoveNotify = 0,
    PKTSkillDamageNotify = 1,
    PKTSkillStageNotify = 0,
    PKTSkillStartNotify = 0,
    PKTStatChangeNotify = 0x8BB0,
    PKTStatChangeOriginNotify = 0,
    PKTStatusEffectAddNotify = 0x50BD,
    PKTStatusEffectDurationNotify = 0,
    PKTStatusEffectRemoveNotify = 0,
    PKTStatusEffectSyncDataNotify = 0,
    PKTTriggerBossBattleStatus = 0,
    PKTTriggerFinishNotify = 0,
    PKTTriggerStartNotify = 0,
    PKTTroopMemberUpdateMinNotify = 0,
    PKTZoneMemberLoadStatusNotify = 0,
    PKTZoneObjectUnpublishNotify = 0,
    PKTZoneStatusEffectAddNotify = 0,
    PKTZoneStatusEffectRemoveNotify = 0,
};
